// brand.http
@BASE_URL = http://localhost:3333
@AUTH_TOKEN = {{authenticate.response.body.access_token}}

# @name authenticate
POST {{BASE_URL}}/sessions
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Adminpassword@8"
}

###

# @name create-brand
POST {{BASE_URL}}/brands
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
  "name": "Brand for testess2",
  "imageUrl": "/icons/no-photos.svg",
  "erpId":"10000"
  
}


###

# @name delete-brands
Delete  {{BASE_URL}}/brands/0369c0a6-308c-45fc-80cf-5514c3abd1d0
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###

# @name find-brands-by-name
GET  {{BASE_URL}}/brands/name?name=PLIE
Content-Type: application/json



###
# @name get-brands-all
GET {{BASE_URL}}/brands/all?page=1&pageSize=10
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}


###


# @name find-brand-by-id
GET  {{BASE_URL}}/brands/040fa9e6-7b3c-44e1-af71-701e8737d023
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###

# @name edit-brand
PUT  {{BASE_URL}}/brands/040fa9e6-7b3c-44e1-af71-701e8737d023
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
  "name": "brand 4",
  "imageUrl": "/icons/logo-nayne.jpeg"
  
}




