@BASE_URL = http://localhost:3333

@AUTH_TOKEN = {{authenticate.response.body.access_token}}

# @name authenticate
POST {{BASE_URL}}/sessions
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Adminpassword@8"
}

###

# @name create-category
POST {{BASE_URL}}/category
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
  "name": "category teste 90",
   "imageUrl": "https://stylos-images-bucket.s3.amazonaws.com/no-photos.svg",
"erpId": "20000"
  
}

###

# @name get-category-by-name
GET  {{BASE_URL}}/category?name=category teste 90
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###

# @name delete-category
Delete  {{BASE_URL}}/category/4428db41-b66c-4bca-9d0d-24dc23cd72cf
Authorization: Bearer {{AUTH_TOKEN}}
Content-Type: application/json

###

# @name find-category-by-id
GET  {{BASE_URL}}/category/53b2af1c-38a2-4f81-94e9-29e3cf8365d7

Content-Type: application/json

###


# @name get-category-all
GET {{BASE_URL}}/category/all?page=1&pageSize=80
Content-Type: application/json
###


# @name get-category-all-withProducts
GET {{BASE_URL}}/category/all-withProducts?page=1&pageSize=80
Content-Type: application/json



###

# @name edit-brand
PUT  {{BASE_URL}}/category/53b2af1c-38a2-4f81-94e9-29e3cf8365d7
Authorization: Bearer {{AUTH_TOKEN}}
Content-Type: application/json

{
  "name": "category 2",
  "imageUrl": "/icons/pijamas-mini.svg"

  }





