@BASE_URL = http://localhost:3333
@AUTH_TOKEN = {{authenticate.response.body.access_token}}

# @name authenticate
POST {{BASE_URL}}/sessions/
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Adminpassword@8"
}

### 

# @name create-color
POST {{BASE_URL}}/colors
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
  "name": "black2",
  "hex":"#000",
  "erpId": "1000"
}

###

# @name find-colors-by-name
GET  {{BASE_URL}}/colors?name=black2
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###

# @name delete-colors
Delete  {{BASE_URL}}/colors/81f6632d-b5d0-4546-8eaf-17fbd5d86aff
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###

# @name find-color-by-id
GET  {{BASE_URL}}/colors/1d13b470-2964-4f4d-baeb-6f9a341ad59c
Content-Type: application/json

###



# @name get-colors-all
GET {{BASE_URL}}/colors/all?page=1&pageSize=80
Content-Type: application/json


###

# @name edit-color
PUT  {{BASE_URL}}/colors/1d13b470-2964-4f4d-baeb-6f9a341ad59c
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
  "name": "vermelhinho",
  "hex":"#690000"
  
}




