@BASE_URL = http://localhost:3333

@AUTH_TOKEN = {{authenticate.response.body.access_token}}


# @name authenticate
POST {{BASE_URL}}/sessions
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Adminpassword@8"
}

###

# @name create-size
POST {{BASE_URL}}/size
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
  "name": "pequena",
  "erpId":"1000"
}

###



# @name delete-size
Delete  {{BASE_URL}}/size/c8d54ee5-28ed-4e19-9340-a63682fb1c4f
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}


###

# @name find-size-by-id
GET  {{BASE_URL}}/size/8f9d5869-ca6c-4bf6-81f9-e3bdf9fd8b19
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###

# @name edit-size
PUT  {{BASE_URL}}/size/8f9d5869-ca6c-4bf6-81f9-e3bdf9fd8b19
Content-Type: application/json

{
  "name": "G"
  
}


###
# @name get-size-all
GET {{BASE_URL}}/size/all?page=1&pageSize=80
Content-Type: application/json






